chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = [
    path('testimonials/<int:pk>/', views.testimonials, name='testimonials'),
    path('feedback/', views.feedback, name='feedback'),
    path("login/",LoginView.as_view(),name='login'),
    path("register/",views.registerView,name='register'),
    path("logout/",LogoutView.as_view(next_page='home'),name='logout'),
    path("home/",views.homeView,name='home'),
    path("index/",views.indexView,name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

src/cfehome/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import PasswordResetView,\
                                      PasswordResetDoneView,\
                                      PasswordResetConfirmView,\
                                      PasswordResetCompleteView

from chat.models import CurrentChatRooms

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('chitchat/', include('chat.urls')),
    re_path(r'^emoji/', include('emoji.urls')),
    # Enter your email and request a password reset here
    path('profile/password-reset/',
         PasswordResetView.as_view(
          template_name="chat/password_reset.html",
          extra_context={"page_name": "Reset Password"}
          ),
         name="password_reset",
         ),

    # Sends the email
    path('profile/password-reset/done/',
         PasswordResetDoneView.as_view(
          template_name="chat/password_reset_done.html",
          extra_context={"page_name": "Link Sent"}
          ),
         name="password_reset_done"
         ),

    # Takes you to the password reset form
    path('profile/password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
          template_name="chat/password_reset_confirm.html",
          extra_context={"page_name": "Password Reset Form"}
          ),
         name="password_reset_confirm"
         ),

    # Final view to complete the password reset process
    path('profile/password-reset-complete/',
         PasswordResetCompleteView.as_view(
          template_name="chat/password_reset_complete.html",
          extra_context={"page_name": "Password Reset Complete"}
          ),
         name="password_reset_complete",
         ),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# Every time the server is started we need to clear the
# contents of the CurrentChatRooms model, so we do that here
CurrentChatRooms.objects.clear_logs()

src/chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView, LoadProfileView, searchUser,\
                   loginUser, signupUser, homePage, logoutUser, edit_profile,\
                   change_password, leaveThreadHandler

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^chatbox/(?P<username>[\w.@+-]+)/$", ThreadView.as_view(),
            name="chatBox"),
    re_path(r"^search/username/$", searchUser, name="searchUser"),
    re_path(r"^login/$", loginUser, name="login"),
    re_path(r"^logout/$", logoutUser, name="logout"),
    re_path(r"^signup/$", signupUser, name="signup"),
    re_path(r"^home/$", homePage, name="home"),
    re_path(r"^profile/edit/$", edit_profile, name="edit_profile"),
    re_path(r"^profile/password/$", change_password,
            name="change_password"),
    path("profile/", LoadProfileView.as_view(), name="profile"),
    path("threads/leave-thread/", leaveThreadHandler, name="leave_thread"),
    # re_path(r'^reset-password/$', password_reset, name='reset_password'),
    # re_path(r'^reset-password/done/$', password_reset_done,
    #         name='password_reset_done'),
    # re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #         password_reset_confirm, name='password_reset_confirm'),
    # re_path(r'^reset-password/complete/$',
    #         password_reset_complete, name='password_reset_complete'),
]

Archive/src/chat/models.py
from django.db import models

from django.conf import settings

from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) &\
            Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) &\
            Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            User_Model_Class = user.__class__
            user2 = User_Model_Class.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True,
                               on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender',
                             on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/models.py
from django.db import models

class Feedback(models.Model):
    ratingTypes=(
        ("Poor","Poor"),
        ("Average","Average"),
        ("Satisfactory","Satisfactory"),
        ("Good","Good"),
        ("Excellent","Excellent"),
    )
    name = models.CharField(max_length=30)
    email = models.EmailField()
    rating  =models.CharField(max_length=20,choices=ratingTypes)
    text = models.CharField(max_length=100)
# Create your models here.

Archive/src/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = "__all__"

src/chat/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm                                    
from django.contrib.auth.models import User

from .models import UserProfile


class ComposeForm(forms.Form):
    message = forms.CharField(
            strip=True,
            widget=forms.TextInput(
                attrs={"class": "form-control",
                       'placeholder': 'Enter your message here'}
            ))


class UserSearchForm(forms.Form):
    username_search = forms.CharField(
        strip=True,
        widget=forms.TextInput(
                attrs={"id": "searchBox",
                       "class": "form-control wide-input",
                       'placeholder': 'Type in the user to chat with here'}
                )
    )


class UserProfileImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image']
        labels = {
            'profile_image': _('Profile Image'),
        }
        help_texts = {
            'profile_image': _('Upload your profile image here.'),
        }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditUserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )

Archive/src/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'
    model = Thread

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user,
                                                 other_username)
        if obj is None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/views.py
from django.shortcuts import render,redirect
from .models import Feedback
from .forms import FeedbackForm
from django.contrib.auth.forms import UserCreationForm
def testimonials(request,pk):
    posts=Feedback.objects.filter(pk=pk)
    return render(request, 'chat/testimonials.html', {'posts':posts})

def feedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('testimonials', pk=post.pk)
    else:
        form = FeedbackForm()
    return render(request, 'chat/feedback.html', {'form': form})   

def indexView(request):
    return render(request,'chat/index.html')

def homeView(request):
    return render(request,'chat/home.html')

def registerView(request):
    if request.method == "POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
            form = UserCreationForm()
    return render(request, 'registration/register.html',{'form':form})

src/chat/templates/chat/change_pwd.html
{% extends 'base.html' %}

{% block style %}
    {% include 'CSS/signup_css.html' %}
    {% include 'CSS/profileIcon_css.html' %}
    {% include 'CSS/div_alert_css.html'%}
{% endblock %}

{% block headings %}
    {% include 'chat/profileIcon.html' %}
{%endblock%}

{% block dropdown %}
    <!--the dropdown menu-->
    <div class="list-group profile-icon-list-group">
        <a href="{% url 'chat:profile' %}" class="list-group-item list-group-item-action profile-icon-dropdown-hide">Profile</a>
        <a href="{% url 'chat:logout' %}" class="list-group-item list-group-item-action profile-icon-dropdown-hide">Logout</a>
    </div>

    <!-- Hidden Logout form -->
    <form action="{% url 'chat:logout' %}" method="post" class="logout-form">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{PWD_Form|crispy}}
        <hr>
        
        <br>
        <div class="d-flex justify-content-end">
            <div class="p-2">
                <button type="submit" class="btn btn-primary">
                    {{btnName_edit}}&nbsp;&nbsp;
                    <svg class="bi bi-pencil" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 011.414 0l2 2a1 1 0 010 1.414l-9 9a1 1 0 01-.39.242l-3 1a1 1 0 01-1.266-1.265l1-3a1 1 0 01.242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 00.5.5H4v.5a.5.5 0 00.5.5H5v.5a.5.5 0 00.5.5H6v-1.5a.5.5 0 00-.5-.5H5v-.5a.5.5 0 00-.5-.5H3z" clip-rule="evenodd"/>
                    </svg>
                </button>
            </div>
            <div class="p-2">
                <button type="button" class="btn btn-dark" id="reset-pwd-email" data-toggle="tooltip" data-placement="top" title="You will be logged out. To complete this action!">
                    {{btnName_email}}
                    <svg class="bi bi-envelope" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M14 3H2a1 1 0 00-1 1v8a1 1 0 001 1h12a1 1 0 001-1V4a1 1 0 00-1-1zM2 2a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V4a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M.071 4.243a.5.5 0 01.686-.172L8 8.417l7.243-4.346a.5.5 0 01.514.858L8 9.583.243 4.93a.5.5 0 01-.172-.686z" clip-rule="evenodd"/>
                        <path d="M6.752 8.932l.432-.252-.504-.864-.432.252.504.864zm-6 3.5l6-3.5-.504-.864-6 3.5.504.864zm8.496-3.5l-.432-.252.504-.864.432.252-.504.864zm6 3.5l-6-3.5.504-.864 6 3.5-.504.864z"/>
                    </svg>
                </button>
            </div>
        </div>
    </form>


    <!-- User alerts -->
    <div class="alert alert-success on-load large" role="alert">
        <p class="text-center font-weight-normal mb-0 pb-0">
            {% if request.GET.status %}
                {% if request.GET.status == 'failure_pwd_chg' %}
                    Password could not be changed, Please try again!&nbsp;&nbsp;&#128561;
                {% endif %}
            {% else %}
                Pro Tip: Longer and easier to remember passwords are better than short and confusing ones.&nbsp;&nbsp;&#129488;
            {% endif %}
        </p>
    </div>
{% endblock %}

{% block script %}
    {% include 'clientSideJS/change_pwd_js.html' %}
    {% include 'clientSideJS/profileIcon_js.html' %}
{% endblock %}

src/chat/templates/chat/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="d-flex flex-column">
        <div class='alert alert-info p-1' style="text-align: center;">
            <strong>Password Reset Complete:</strong>&nbsp;
            Your Password has been Reset.
        </div>
        <br>
        <div class="d-flex justify-content-end">
            <a href="{% url 'chat:login' %}">Sign In Here</a>
        </div>
    </div>
{% endblock %}

src/chat/templates/chat/profile.html
{% extends "base.html" %}

{% block style %}
    {% include 'CSS/profile_css.html' %}
    {% include 'CSS/profileIcon_css.html' %}
    {% include 'CSS/div_alert_css.html'%}
{% endblock %}


{% block headings %}
    {% include 'chat/profileIcon.html' %}
{%endblock%}

{% block dropdown %}
    <!--the dropdown menu-->
    <div class="list-group profile-icon-list-group">
        <a href="{% url 'chat:edit_profile' %}" class="list-group-item list-group-item-action profile-icon-dropdown-hide">Edit Profile</a>
        <a href="{% url 'chat:logout' %}" class="list-group-item list-group-item-action profile-icon-dropdown-hide">Logout</a>
    </div>

    <!-- Hidden Logout form -->
    <form action="{% url 'chat:logout' %}" method="post" class="logout-form">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% load emoji_tags %}

<!-- Allow the user to search for other users -->
<div class="d-flex flex-column">
    <div class="p-2">
        <div class="d-md-flex justify-content-between">
            <div class="p-1">
                <div class="card">
                    <div class="card-body">
                        <ul class="description">
                            <li>Find new users, form the search menu provided.</li>
                            <li>Only the top 10 results are returned.</li>
                            <li>We hope you find whomever you are looking for &#128516;.</li>
                        </ul>
                    </div>
                  </div>
            </div>
            <div class="p-1">
                <form method="post" class="form-inline" id="searchForm">{% csrf_token %}
                    <input type="hidden" value="{{ user.username }}" id="myUsername"/>
                    <div class="form-group mx-sm-3 mb-2">
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-danger" id="search_button">
                        Clear&nbsp;&nbsp;
                        <svg class="bi bi-backspace" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M6.603 2h7.08a1 1 0 011 1v10a1 1 0 01-1 1h-7.08a1 1 0 01-.76-.35L1 8l4.844-5.65A1 1 0 016.603 2zm7.08-1a2 2 0 012 2v10a2 2 0 01-2 2h-7.08a2 2 0 01-1.519-.698L.241 8.65a1 1 0 010-1.302L5.084 1.7A2 2 0 016.603 1h7.08z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M5.83 5.146a.5.5 0 000 .708l5 5a.5.5 0 00.707-.708l-5-5a.5.5 0 00-.708 0z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M11.537 5.146a.5.5 0 010 .708l-5 5a.5.5 0 01-.708-.708l5-5a.5.5 0 01.707 0z" clip-rule="evenodd"/>
                          </svg>
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div class="p-2">
        <div class="d-md-flex justify-content-around">
            <div class="p-1">
                
            </div>
            <div class="p-1 align-under-search">
                <div class="list-group d-inline-flex p-2">
                    <h3 class="results-title">Matching search results:</h3>
                    <div class="alert alert-danger" role="alert" id="noUserFoundMessage">
                        <svg class="bi bi-exclamation-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z" clip-rule="evenodd"/>
                            <path d="M7.002 11a1 1 0 112 0 1 1 0 01-2 0zM7.1 4.995a.905.905 0 111.8 0l-.35 3.507a.552.552 0 01-1.1 0L7.1 4.995z"/>
                        </svg>&nbsp;&nbsp;
                        No matching user found!
                    </div>
                    <div class="alert alert-danger" role="alert" id="searchingUserFoundMessage">
                        <svg class="bi bi-exclamation-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z" clip-rule="evenodd"/>
                            <path d="M7.002 11a1 1 0 112 0 1 1 0 01-2 0zM7.1 4.995a.905.905 0 111.8 0l-.35 3.507a.552.552 0 01-1.1 0L7.1 4.995z"/>
                        </svg>&nbsp;&nbsp;
                        Why are you searching for yourself. You are {{user.username}}
                    </div>
                    <div class="users list-group"></div>
                </div>
            </div>
	    </div>
    </div>
</div>

<!-- Show the user the existing chat threads -->
<div class='container'>
    <div class='d-flex border-bottom my-3 py-3 flex-row justify-content-between align-items-stretch'>
        <div class='p-1'>
            <h1 class='p-0 m-0'>Your Existing Threads</h1>
        </div>
    </div>
        {% comment "We first check if the user has any previous chat threads" %}{% endcomment %}
        {% if userChatList %}
            {% comment "If they have previous threads, then we display them" %}{% endcomment %}
            {% for user1, user2 in userChatList %}
            <div class="d-flex my-3 py-3 flex-row justify-content-between align-items-stretch">
                {% if user1 %}
                    <div class="col-sm-6">
                        <div>
                            <a href="{% url 'chat:chatBox' user1.other_user %}" class="chat-link" target="_blank">
                                <div class="card text-center text-white bg-dark mb-3 shadow-animated full-size">
                                    <div class="card-header">
                                        <b class="align-bottom">Thread with:</b>&nbsp;&nbsp;
                                        <span class="badge badge-pill badge-light user-size align-bottom">{{ user1.other_user }}</span>
                                    </div>
                                    <div class="card-body">
                                        <div class="card-text d-flex justify-content-center message-text full-size"><b>{{ user1.latest_message.user }}</b>&nbsp;&nbsp;-&nbsp;&nbsp;{{ user1.latest_message.message | emoji_replace }}</div>
                                    </div>
                                    <div class="card-footer">
                                        {{ user1.latest_message.timestamp }}
                                    </div>
                                </div>
                            </a>
                            <button type="button" class="btn btn-danger fill" user="{{user.username}}" other_user="{{user1.other_user}}" id="delete-button">
                                Delete Thread with {{user1.other_user}}&nbsp;&nbsp;
                                <svg class="bi bi-trash-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M2.5 1a1 1 0 00-1 1v1a1 1 0 001 1H3v9a2 2 0 002 2h6a2 2 0 002-2V4h.5a1 1 0 001-1V2a1 1 0 00-1-1H10a1 1 0 00-1-1H7a1 1 0 00-1 1H2.5zm3 4a.5.5 0 01.5.5v7a.5.5 0 01-1 0v-7a.5.5 0 01.5-.5zM8 5a.5.5 0 01.5.5v7a.5.5 0 01-1 0v-7A.5.5 0 018 5zm3 .5a.5.5 0 00-1 0v7a.5.5 0 001 0v-7z" clip-rule="evenodd" />
                                </svg>
                            </button>
                        </div>
                    </div>
                {% endif %}
                {% if user2 %}
                <div class="col-sm-6">
                    <div>
                        <a href="{% url 'chat:chatBox' user2.other_user %}" rel="noopener noreferrer" class="chat-link" target="_blank">
                            <div class="card text-center text-white bg-dark mb-3 shadow-animated full-size">
                                <div class="card-header">
                                    <b class="align-bottom">Thread with:</b>&nbsp;&nbsp;
                                    <span class="badge badge-pill badge-light user-size align-bottom">{{ user2.other_user }}</span>
                                </div>
                                <div class="card-body">
                                    <div class="card-text d-flex justify-content-center message-text full-size"><b>{{ user2.latest_message.user }}</b>&nbsp;&nbsp;-&nbsp;&nbsp;{{ user2.latest_message.message | emoji_replace }}</div>
                                </div>
                                <div class="card-footer">
                                    {{ user2.latest_message.timestamp }}
                                </div>
                            </div>
                        </a>
                        <button type="button" class="btn btn-danger fill" user="{{user.username}}" other_user="{{user2.other_user}}" id="delete-button">
                            Delete Thread with {{user2.other_user}}&nbsp;&nbsp;
                            <svg class="bi bi-trash-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M2.5 1a1 1 0 00-1 1v1a1 1 0 001 1H3v9a2 2 0 002 2h6a2 2 0 002-2V4h.5a1 1 0 001-1V2a1 1 0 00-1-1H10a1 1 0 00-1-1H7a1 1 0 00-1 1H2.5zm3 4a.5.5 0 01.5.5v7a.5.5 0 01-1 0v-7a.5.5 0 01.5-.5zM8 5a.5.5 0 01.5.5v7a.5.5 0 01-1 0v-7A.5.5 0 018 5zm3 .5a.5.5 0 00-1 0v7a.5.5 0 001 0v-7z" clip-rule="evenodd" />
                            </svg>
                        </button>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-danger" role="alert">
                Looks like you have not started any chat, search for a user and begin chatting.&nbsp;&nbsp;&#128515;
            </div>
        {% endif %}
</div>


<!-- User alerts -->
<div class="alert alert-success on-load medium" role="alert">
    <p class="text-center font-weight-normal mb-0 pb-0">
        {% if request.GET.status %}
            {% if request.GET.status == 'success_pwd_chg' %}
                Password Changed Successfully!&nbsp;&nbsp;&#128516;
            {% elif request.GET.status == 'success_det_chg' %}
                User Details Changed Successfully!&nbsp;&nbsp;&#128516;
            {% elif request.GET.status == 'success_user_login' %}
                Nice to see you again {{object.username}}.&nbsp;&nbsp;&#128526;
            {% elif request.GET.status == 'success_user_register' %}
                Hi, there! Welcome to ChitChat!&nbsp;&nbsp;&#128525;
            {% elif request.GET.status == 'user_already_logged_in' %}
                Hey! Your already logged in!&nbsp;&nbsp;&#128514;
            {% endif %}
        {% else %}
            Welcome back {{object.username}}.&nbsp;&nbsp;&#128512;
        {% endif %}
    </p>
</div>

{% endblock %}

{% block script %}
    {% include 'clientSideJS/profile_js.html' %}
    {% include 'clientSideJS/profileIcon_js.html' %}
{% endblock %}