chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = [
    path('testimonials/<int:pk>/', views.testimonials, name='testimonials'),
    path('feedback/', views.feedback, name='feedback'),
    path("login/",LoginView.as_view(),name='login'),
    path("register/",views.registerView,name='register'),
    path("logout/",LogoutView.as_view(next_page='home'),name='logout'),
    path("home/",views.homeView,name='home'),
    path("index/",views.indexView,name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

src/cfehome/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import PasswordResetView,\
                                      PasswordResetDoneView,\
                                      PasswordResetConfirmView,\
                                      PasswordResetCompleteView

from chat.models import CurrentChatRooms

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('chitchat/', include('chat.urls')),
    re_path(r'^emoji/', include('emoji.urls')),
    # Enter your email and request a password reset here
    path('profile/password-reset/',
         PasswordResetView.as_view(
          template_name="chat/password_reset.html",
          extra_context={"page_name": "Reset Password"}
          ),
         name="password_reset",
         ),

    # Sends the email
    path('profile/password-reset/done/',
         PasswordResetDoneView.as_view(
          template_name="chat/password_reset_done.html",
          extra_context={"page_name": "Link Sent"}
          ),
         name="password_reset_done"
         ),

    # Takes you to the password reset form
    path('profile/password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
          template_name="chat/password_reset_confirm.html",
          extra_context={"page_name": "Password Reset Form"}
          ),
         name="password_reset_confirm"
         ),

    # Final view to complete the password reset process
    path('profile/password-reset-complete/',
         PasswordResetCompleteView.as_view(
          template_name="chat/password_reset_complete.html",
          extra_context={"page_name": "Password Reset Complete"}
          ),
         name="password_reset_complete",
         ),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# Every time the server is started we need to clear the
# contents of the CurrentChatRooms model, so we do that here
CurrentChatRooms.objects.clear_logs()

src/chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView, LoadProfileView, searchUser,\
                   loginUser, signupUser, homePage, logoutUser, edit_profile,\
                   change_password, leaveThreadHandler

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^chatbox/(?P<username>[\w.@+-]+)/$", ThreadView.as_view(),
            name="chatBox"),
    re_path(r"^search/username/$", searchUser, name="searchUser"),
    re_path(r"^login/$", loginUser, name="login"),
    re_path(r"^logout/$", logoutUser, name="logout"),
    re_path(r"^signup/$", signupUser, name="signup"),
    re_path(r"^home/$", homePage, name="home"),
    re_path(r"^profile/edit/$", edit_profile, name="edit_profile"),
    re_path(r"^profile/password/$", change_password,
            name="change_password"),
    path("profile/", LoadProfileView.as_view(), name="profile"),
    path("threads/leave-thread/", leaveThreadHandler, name="leave_thread"),
    # re_path(r'^reset-password/$', password_reset, name='reset_password'),
    # re_path(r'^reset-password/done/$', password_reset_done,
    #         name='password_reset_done'),
    # re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #         password_reset_confirm, name='password_reset_confirm'),
    # re_path(r'^reset-password/complete/$',
    #         password_reset_complete, name='password_reset_complete'),
]

Archive/src/chat/models.py
from django.db import models

from django.conf import settings

from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) &\
            Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) &\
            Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            User_Model_Class = user.__class__
            user2 = User_Model_Class.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True,
                               on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender',
                             on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/models.py
from django.db import models

class Feedback(models.Model):
    ratingTypes=(
        ("Poor","Poor"),
        ("Average","Average"),
        ("Satisfactory","Satisfactory"),
        ("Good","Good"),
        ("Excellent","Excellent"),
    )
    name = models.CharField(max_length=30)
    email = models.EmailField()
    rating  =models.CharField(max_length=20,choices=ratingTypes)
    text = models.CharField(max_length=100)
# Create your models here.

Archive/src/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = "__all__"

src/chat/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm                                    
from django.contrib.auth.models import User

from .models import UserProfile


class ComposeForm(forms.Form):
    message = forms.CharField(
            strip=True,
            widget=forms.TextInput(
                attrs={"class": "form-control",
                       'placeholder': 'Enter your message here'}
            ))


class UserSearchForm(forms.Form):
    username_search = forms.CharField(
        strip=True,
        widget=forms.TextInput(
                attrs={"id": "searchBox",
                       "class": "form-control wide-input",
                       'placeholder': 'Type in the user to chat with here'}
                )
    )


class UserProfileImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image']
        labels = {
            'profile_image': _('Profile Image'),
        }
        help_texts = {
            'profile_image': _('Upload your profile image here.'),
        }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditUserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )

Archive/src/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'
    model = Thread

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user,
                                                 other_username)
        if obj is None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/views.py
from django.shortcuts import render,redirect
from .models import Feedback
from .forms import FeedbackForm
from django.contrib.auth.forms import UserCreationForm
def testimonials(request,pk):
    posts=Feedback.objects.filter(pk=pk)
    return render(request, 'chat/testimonials.html', {'posts':posts})

def feedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('testimonials', pk=post.pk)
    else:
        form = FeedbackForm()
    return render(request, 'chat/feedback.html', {'form': form})   

def indexView(request):
    return render(request,'chat/index.html')

def homeView(request):
    return render(request,'chat/home.html')

def registerView(request):
    if request.method == "POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
            form = UserCreationForm()
    return render(request, 'registration/register.html',{'form':form})

Archive/src/chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

Archive/src/chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}

<style>
    ul {list-style-type: none;}
    .card-body { overflow-y: auto; max-height: 500px;}
</style>
<div class="card" id="chat-box">
    <div class="card-header">
        Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush" id='chat-items'>
            {% for chat in object.chatmessage_set.all %}
                <li class="list-group-item"><svg class="bi bi-person-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
                    <path fill-rule="evenodd" d="M2 15v-1c0-1 1-4 6-4s6 3 6 4v1H2zm6-6a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"/>
                  </svg> <b class="text-muted">{{ chat.user }}</b> - {{ chat.message }}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="card-footer text-muted">
        <form id='form' method='POST'> {% csrf_token %}
            <input type="hidden" value="{{ user.username }}" id="myUsername"/>
            {{form.as_p }}
            <input type='submit' class='btn btn-block btn-primary'/>
        </form>
    </div>
</div>


{% endblock %}

{% block script %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>

<script>
// websocket scripts
console.log(window.location)

var loc = window.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()

formData.attr('autocomplete', 'off')

var wsStart = 'ws://'
if(loc.protocol == 'https:') {
    wsStart = 'wss://'
}
var endpoint = wsStart + loc.host + loc.pathname
var sockets = new ReconnectingWebSocket(endpoint)

sockets.onmessage = function(e) {
    console.log('message', e)

    // Parsing the new chat data which contains
    // 1. The message itself
    // 2. The user who authored the message
    let newChatData = JSON.parse(e.data)

    /*For the messages by other users we need to communicate with backend*/
    // creating an entry for a new message on the Browser window
    let messageEntry = document.createElement("li")
    messageEntry.textContent = "[" + newChatData.username + "] " + newChatData.message
    // console.log(messageEntry)
    // Putting the created entry on the DOM
    chatHolder.append(messageEntry)
    
}
sockets.onopen = function(e) {
    console.log('open', e)
    formData.submit(function(event){
        event.preventDefault()
        let msgText = msgInput.val()

        let finalData = {
            'message': msgText
        }
        sockets.send(JSON.stringify(finalData))
        formData[0].reset()
    })
}
sockets.onerror = function(e) {
    console.log('error', e)
}
sockets.onclose = function(e) {
    console.log('close', e)
}
</script>
{% endblock %}