chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = [
    path('testimonials/<int:pk>/', views.testimonials, name='testimonials'),
    path('feedback/', views.feedback, name='feedback'),
    path("login/",LoginView.as_view(),name='login'),
    path("register/",views.registerView,name='register'),
    path("logout/",LogoutView.as_view(next_page='home'),name='logout'),
    path("home/",views.homeView,name='home'),
    path("index/",views.indexView,name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

src/cfehome/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import PasswordResetView,\
                                      PasswordResetDoneView,\
                                      PasswordResetConfirmView,\
                                      PasswordResetCompleteView

from chat.models import CurrentChatRooms

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('chitchat/', include('chat.urls')),
    re_path(r'^emoji/', include('emoji.urls')),
    # Enter your email and request a password reset here
    path('profile/password-reset/',
         PasswordResetView.as_view(
          template_name="chat/password_reset.html",
          extra_context={"page_name": "Reset Password"}
          ),
         name="password_reset",
         ),

    # Sends the email
    path('profile/password-reset/done/',
         PasswordResetDoneView.as_view(
          template_name="chat/password_reset_done.html",
          extra_context={"page_name": "Link Sent"}
          ),
         name="password_reset_done"
         ),

    # Takes you to the password reset form
    path('profile/password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
          template_name="chat/password_reset_confirm.html",
          extra_context={"page_name": "Password Reset Form"}
          ),
         name="password_reset_confirm"
         ),

    # Final view to complete the password reset process
    path('profile/password-reset-complete/',
         PasswordResetCompleteView.as_view(
          template_name="chat/password_reset_complete.html",
          extra_context={"page_name": "Password Reset Complete"}
          ),
         name="password_reset_complete",
         ),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# Every time the server is started we need to clear the
# contents of the CurrentChatRooms model, so we do that here
CurrentChatRooms.objects.clear_logs()

src/chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView, LoadProfileView, searchUser,\
                   loginUser, signupUser, homePage, logoutUser, edit_profile,\
                   change_password, leaveThreadHandler

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^chatbox/(?P<username>[\w.@+-]+)/$", ThreadView.as_view(),
            name="chatBox"),
    re_path(r"^search/username/$", searchUser, name="searchUser"),
    re_path(r"^login/$", loginUser, name="login"),
    re_path(r"^logout/$", logoutUser, name="logout"),
    re_path(r"^signup/$", signupUser, name="signup"),
    re_path(r"^home/$", homePage, name="home"),
    re_path(r"^profile/edit/$", edit_profile, name="edit_profile"),
    re_path(r"^profile/password/$", change_password,
            name="change_password"),
    path("profile/", LoadProfileView.as_view(), name="profile"),
    path("threads/leave-thread/", leaveThreadHandler, name="leave_thread"),
    # re_path(r'^reset-password/$', password_reset, name='reset_password'),
    # re_path(r'^reset-password/done/$', password_reset_done,
    #         name='password_reset_done'),
    # re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #         password_reset_confirm, name='password_reset_confirm'),
    # re_path(r'^reset-password/complete/$',
    #         password_reset_complete, name='password_reset_complete'),
]

Archive/src/chat/models.py
from django.db import models

from django.conf import settings

from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) &\
            Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) &\
            Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            User_Model_Class = user.__class__
            user2 = User_Model_Class.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True,
                               on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender',
                             on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/models.py
from django.db import models

class Feedback(models.Model):
    ratingTypes=(
        ("Poor","Poor"),
        ("Average","Average"),
        ("Satisfactory","Satisfactory"),
        ("Good","Good"),
        ("Excellent","Excellent"),
    )
    name = models.CharField(max_length=30)
    email = models.EmailField()
    rating  =models.CharField(max_length=20,choices=ratingTypes)
    text = models.CharField(max_length=100)
# Create your models here.

Archive/src/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = "__all__"

src/chat/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm                                    
from django.contrib.auth.models import User

from .models import UserProfile


class ComposeForm(forms.Form):
    message = forms.CharField(
            strip=True,
            widget=forms.TextInput(
                attrs={"class": "form-control",
                       'placeholder': 'Enter your message here'}
            ))


class UserSearchForm(forms.Form):
    username_search = forms.CharField(
        strip=True,
        widget=forms.TextInput(
                attrs={"id": "searchBox",
                       "class": "form-control wide-input",
                       'placeholder': 'Type in the user to chat with here'}
                )
    )


class UserProfileImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image']
        labels = {
            'profile_image': _('Profile Image'),
        }
        help_texts = {
            'profile_image': _('Upload your profile image here.'),
        }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditUserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )

Archive/src/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'
    model = Thread

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user,
                                                 other_username)
        if obj is None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/views.py
from django.shortcuts import render,redirect
from .models import Feedback
from .forms import FeedbackForm
from django.contrib.auth.forms import UserCreationForm
def testimonials(request,pk):
    posts=Feedback.objects.filter(pk=pk)
    return render(request, 'chat/testimonials.html', {'posts':posts})

def feedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('testimonials', pk=post.pk)
    else:
        form = FeedbackForm()
    return render(request, 'chat/feedback.html', {'form': form})   

def indexView(request):
    return render(request,'chat/index.html')

def homeView(request):
    return render(request,'chat/home.html')

def registerView(request):
    if request.method == "POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
            form = UserCreationForm()
    return render(request, 'registration/register.html',{'form':form})

src/chat/templates/clientSideJS/change_pwd_js.html
<script>
    // Calling the tooltip function for the user profile hover-username effect
    $('button#reset-pwd-email').tooltip();  

    $("button#reset-pwd-email").click(function(e) {
        window.location.href = "{% url 'password_reset' %}"
    })
</script>

src/chat/templates/clientSideJS/profileIcon_js.html
<script>
    // Togglling the green dot on the user profile icon
    // and showing the dropdown options
    $("div#userProfile").click(function() {
        $("div#alert").toggleClass("green_icon");
        $("div.list-group.profile-icon-list-group").children().toggleClass("profile-icon-dropdown-hide")
    })

    // when a dropdown item is clicked then we need to make it active
    $("div.list-group.profile-icon-list-group").children().click(function(e) {
        // We need to figure out what dropdown item was clicked
        // If the logout button was clicked then log the user out
        // by submitting the logout form
        if(e.target.textContent == "Logout") {
            e.preventDefault()
            $("form.logout-form").submit()
        }

        e.target.classList.add("active")
    })

    // If the escape key is pressed the dropdown is hidden
    $(document).keyup(function(e) {
        if(e.keyCode == 27){
            $("div#alert").toggleClass("green_icon");
            $("div.list-group.profile-icon-list-group").children().addClass("profile-icon-dropdown-hide");
        }
    });

    $(document).dblclick(function(event) {
        $("div#alert").toggleClass("green_icon");
        $("div.list-group.profile-icon-list-group").children().addClass("profile-icon-dropdown-hide");
        event.preventDefault()
    })

    // Calling the tooltip function for the user profile hover-username effect
    $('div#userProfile[data-toggle="tooltip"]').tooltip();  

    // Clicking on the user link takes you back to the profile page
    // profileIcon.click(function(e) {
    //     window.location.href = "{% url 'chat:profile' %}";
    // }) 
</script>

src/chat/templates/clientSideJS/profile_js.html
<script>

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
        
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    var csrftoken = getCookie('csrftoken');

//------------------------------------------------------------------------------------------------
    // Getting the URL we need from Django and tricking it with a false username parameter so that it works!
    const BASE_URL = "{% url 'chat:chatBox' 123 %}"
    function listUsers(item, index) {
        // Replacing the dummy parameter with a actual parameter that we need
        let temp = BASE_URL
        temp = temp.replace('123', item);
        $("div.users.list-group").append(`<a href="${temp}" class="list-group-item list-group-item-action" target="_blank"> 
                                            ${item}&nbsp;&nbsp;
                                            <svg class="bi bi-chat-dots" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="margin-bottom: 0.2rem;">
                                                <path fill-rule="evenodd" d="M2.678 11.894a1 1 0 01.287.801 10.97 10.97 0 01-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 01.71-.074A8.06 8.06 0 008 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 01-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 00.244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 01-2.347-.306c-.52.263-1.639.742-3.468 1.105z" clip-rule="evenodd"/>
                                                <path d="M5 8a1 1 0 11-2 0 1 1 0 012 0zm4 0a1 1 0 11-2 0 1 1 0 012 0zm4 0a1 1 0 11-2 0 1 1 0 012 0z"/>
                                            </svg>
                                        </a>`);
    }

    function noUserFound() {
        $("div#noUserFoundMessage").css("display", "block")
    }

    function removeFromDOM(index) {
        $( this ).remove();
    }

    function clearPreviousSearch() {
        // Hide the error messages
        $("div#noUserFoundMessage").css("display", "none")
        $("div#searchingUserFoundMessage").css("display", "none")
        $("h3.results-title").css("display", "none")

        // Check if the users div contains any entries
        // If so then delete them
        oldUserList = $("div.users.list-group").children()
        console.log(oldUserList.length)
        if(oldUserList.length) {
            oldUserList.each(removeFromDOM)
        }
    }

    $("#searchBox").keyup(function(e) {
        // If the enter key is pressed then I want to blur the
        // search box
        if(e.keyCode == 13) {
            $("#searchBox").blur();
        }
    })
    
    let me = $("#myUsername").val()
    $("#searchBox").change(function(e) {
        console.log("Search Box contents updated!")
        console.log("The search string is '" + e.target.value + "'")
        searchString = e.target.value
        // Convert the search string to lowercase
        searchString = searchString.toLowerCase()
    
        userSearchRequest = {
            "searchString": searchString,
        }

        // clear previous results and error messages
        clearPreviousSearch()

        // If the search string is valid
        if(searchString.trim() && searchString != me) {
            $.ajax({
                type: "POST",
                url:"/chitchat/search/username/",
                dataType: "json",
                data: userSearchRequest,
                success: function(data) {
                    console.log(data)
                    console.log("Length of the user list: " + data.userList.length)
                    if(data.userList.length != 0){
                        // Setup the result list
                        $("h3.results-title").css("display", "block")
                        data.userList.forEach(listUsers);
                    }
                    else {
                        // Setup the result list
                        $("h3.results-title").css("display", "block")
                        noUserFound()
                    }
                },

            });
        }
        else if(searchString == me) {
            // Setup the result list
            $("h3.results-title").css("display", "block")
            $("div#searchingUserFoundMessage").css("display", "block")
        }
    
    });

    let = searchForm = $("form#searchForm")
    searchForm.submit(function(event) {
        // Don't submit the form to Django
        event.preventDefault()
        clearPreviousSearch()
        searchForm[0].reset()
    })

//---------------------------------------------------------------------------

$("button#delete-button").click(function(event) {
    let a = event.target.getAttribute("user")
    let b = event.target.getAttribute("other_user")

    dataText = {
            "user": a,
            "other_user": b
            }

    $.ajax({
            type: "POST",
            url:"/chitchat/threads/leave-thread/",
            dataType: "json",
            data: dataText,
            success: function(data) {
                console.log(data)
                console.log("Status: " + data.status)
                if(data.status == 200){
                    console.log("Success")
                    let temp = event.target.parentElement
                    console.log(temp)
                    temp.remove()
                }
                else {
                    console.log("Failure")
                }
            },
        });
})
</script>

src/chat/templates/clientSideJS/threads_js.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>
{% load static %}
{% load emoji_tags %}
    <script src="{% static 'emoji/js/emoji.js' %}"></script>

<script>
    Emoji.setDataUrl('{% url 'emoji:list.json' %}').load();

    // websocket scripts
    console.log(window.location)

    let scrollAllowed = true

    var loc = window.location
    var formData = $("#form")
    var msgInput = $("#id_message")
    var submitButton = $("#submit_button")
    var chatHolder = $("#chat-items")
    var chatHolderDiv = $("#chat-items-div")
    var me = $("#myUsername").val()
    var profileIcon = $("div.image_outer_container")

    formData.attr('autocomplete', 'off')
    chatHolderDiv.scrollTop(chatHolder.height())

    var wsStart = 'ws://'
    if(loc.protocol == 'https:') {
        wsStart = 'wss://'
    }
    var endpoint = wsStart + loc.host + loc.pathname
    var sockets = new ReconnectingWebSocket(endpoint)

    function createSVGTag() {
        ele = `<svg class="bi bi-person-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"/><path fill-rule="evenodd" d="M2 15v-1c0-1 1-4 6-4s6 3 6 4v1H2zm6-6a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"/></svg>`

        return ele
    }

    function createLiTag(username) {
        // getting the current user
        let me = "{{ user }}"
        let ele = document.createElement("li")
        ele.setAttribute("class", "message-spacing list-group-item")
         // If I am the username then my li needs to have the class of list-group-item
         if(me == username) {
            // We have nothing to do here right now, but can use this in the future
        } else { // If I am the not the username then my li needs to have the class of list-group-item-secondary
            ele.classList.add("list-group-item-secondary")
        }
        return ele
    }

    function createTextLine(username, message) {  
        let ele = document.createElement("span")
        let ele_b = document.createElement("b")
        ele_b.setAttribute("class", "text-muted")
        ele_b.textContent = username
        ele.append(ele_b, " - ")
        ele.innerHTML += message
        return ele
    }

    function createMessageLine(username, message) {
        let SVGParent = createSVGTag(), liTag = createLiTag(username)
        let messageLine = createTextLine(username, message)
        liTag.innerHTML = SVGParent + " "
        liTag.append(messageLine)
        return liTag
    }

    sockets.onmessage = function(e) {
        console.log('message', e)

        // getting the current user
        let me = "{{ user }}"
        // Incrementing the count of the number of messages
        let msgCountEle = $("span#message-count")
        let msgCount = Number(msgCountEle.text())
        ++msgCount
        // Update the counter
        msgCountEle.text(msgCount)
        
        // Checking the grammar of the Message(s) text displayed
        let msgTextEle = $("span#message-pluralize")
        let msgText = $.trim(msgTextEle.text())
        if(msgText == "Message" && msgCount != 1) {
            msgTextEle.text("Messages")
        } else if (msgText == "Messages" && msgCount == 1) {
            msgTextEle.text("Message")
        }

        // Parsing the new chat data which contains
        // 1. The message itself
        // 2. The user who authored the message
        let newChatData = JSON.parse(e.data)

        /*For the messages by other users we need to communicate with backend*/
        // creating an entry for a new message on the Browser window
        // console.log(Emoji.replace(newChatData.message))
        let messageEntry = createMessageLine(newChatData.username, Emoji.replace(newChatData.message))
        // console.log(messageEntry)
        // Putting the created entry on the DOM
        chatHolder.append(messageEntry)

       
        // If we have typed a message or if scrollAllowed == true, we get scrolled to the bottom
        // of the chat thread
        if(me == newChatData.username || scrollAllowed == true) {
            // Scroll to the bottom of the chat div
            chatHolderDiv.scrollTop(chatHolder.height())
        }
    }
    sockets.onopen = function(e) {
        console.log('open', e)
        formData.submit(function(event){
            event.preventDefault()
            let msgText = $.trim(msgInput.val())

            let finalData = {
                'message': msgText
            }
            sockets.send(JSON.stringify(finalData))
            formData[0].reset()
        })
    }
    sockets.onerror = function(e) {
        console.log('error', e)
    }
    sockets.onclose = function(e) {
    console.log('close', e)
}

         // If our mouse is hovering in the message thread div then don't scroll down
        // this is set by the scrollAllowed variable
        $( "div#chat-items-div" ).hover(
        function() {
            scrollAllowed = false
        }, function() {
            scrollAllowed = true
        }
        );

</script>